[package]
name = "spline"
version = "0.1.0"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/bodoni/spline"
homepage = "https://github.com/bodoni/spline"
documentation = "https://bodoni.github.io/spline"
description = "The package provides splines."
